server:
  port: 8080

openai:
  key: yourOpenAIKey

application:
  security:
    jwt:
      secret-key: secretKey
      expiration: 86400000 # a day


spring:

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: clientID
            client-secret: clientSecret
      resourceserver:
        jwt:
          issuer-uri: accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs


  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/yourDatabaseName
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver








